services:
  # ----------------------------------------------------
  # 1. アプリケーションコンテナ (PHP-FPM 8.4)
  # ----------------------------------------------------
  src:
    # ./infra/php/Dockerfile を使用してイメージをビルド
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    # 命名は任意
    container_name: src
    # コンテナ内のデフォルト作業ディレクトリ
#    working_dir: /var/www/html/src
    working_dir: /var/www/src
    # ホストの現在のディレクトリ(Laravelプロジェクトルート)をコンテナ内の/var/www/html/srcにマウント
    volumes:
      # - ./src:/var/www/html/src
      - ./src:/var/www/src
    # Nginxと通信するために、同じネットワークに接続、命名は任意
    networks:
      - laravel_network

  # ----------------------------------------------------
  # 2. WEBサーバーコンテナ(Nginx)
  # ----------------------------------------------------

  nginx:
    # 最新の安定版を読み込む
    image: nginx:stable-alpine
    # 命名は任意
    container_name: nginx
    # ホストOSの8080をコンテナ内のポート80にマウント
    ports:
      - "8080:80"
    volumes:
      # srcのLaravelのコードをnginxにもマウント
        - .:/var/www/src
      # Nginxの設定ファイルをコンテナ内にバインドマウント
        - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    # PHP-FPMが起動してから起動する
    depends_on:
      - src

networks:
  laravel_network:
    driver: bridge